# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: daily
      time: "05:30" # UTC
    open-pull-requests-limit: 20
    rebase-strategy: auto
    versioning-strategy: auto
    labels: ["dependencies", "rust"]

  - package-ecosystem: "npm"
    directory: "/vacs-client"
    schedule:
      interval: daily
      time: "06:00" # UTC
    open-pull-requests-limit: 20
    rebase-strategy: auto
    versioning-strategy: increase
    labels: ["dependencies", "node"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "06:30" # UTC
    open-pull-requests-limit: 10
    rebase-strategy: auto
    labels: ["dependencies"]

  - package-ecosystem: "docker"
    directory: "/vacs-server"
    schedule:
      interval: weekly
      day: friday
      time: "07:00" # UTC
    open-pull-requests-limit: 10
    rebase-strategy: auto
    labels: ["dependencies"]
