[package]
name = "vacs-macros"
version = "0.2.0"
edition.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
