name: CI â€¢ Node

on:
  pull_request:
    branches: [ main, v2 ]
    paths:
      - 'vacs-client/frontend/**'
      - '!vacs-client/frontend/icons/**'
      - '.github/workflows/ci-node.yml'
  push:
    branches: [ main, v2 ]
    paths:
      - 'vacs-client/frontend/**'
      - '!vacs-client/frontend/icons/**'
      - '.github/workflows/ci-node.yml'

permissions:
  contents: read

concurrency:
  group: node-ci-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vacs-client

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node (LTS)
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: vacs-client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run -w frontend typecheck

      - name: Lint
        run: npm run -w frontend lint

      - name: Format
        run: npm run format:check